// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zasqarwxwplrbotbjnkc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inphc3Fhcnd4d3BscmJvdGJqbmtjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzE2NzIyMDUsImV4cCI6MjA4NzI0ODIwNX0.74-QWNK6eD3-xjuKTSEjNjLZN-HYfnPwg_6hLRLuisY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});